net.ipv6 = false
net.listen('127.0.0.1', 5354, { kind = 'dns' })
trust_anchors.remove('.')
option('NO_MINIMIZE', true)
cache.size = 256 * MB
modules.load('hints > iterate')
hints.root({ ['a.root-servers.net.'] = '198.41.0.4' })
