options {
    directory "__RUN__";
    listen-on port 5354 { 127.0.0.1; };
    listen-on-v6 { none; };
    recursion yes;
    allow-query { any; };
    allow-recursion { any; };
    dnssec-validation no;
    qname-minimization off;
    max-cache-size 256m;
    pid-file none;
    minimal-responses yes;
};
zone "." { type hint; file "__DIR__/root.hints"; };
