server:
    interface: 127.0.0.1@5354
    num-threads: 1
    do-ip6: no
    username: ""
    chroot: ""
    directory: "__RUN__"
    pidfile: ""
    use-syslog: no
    logfile: ""
    verbosity: 0
    root-hints: "__DIR__/root.hints"
    module-config: "iterator"
    qname-minimisation: no
    msg-cache-size: 128m
    rrset-cache-size: 256m
    so-rcvbuf: 8m
    so-sndbuf: 8m
    outgoing-range: 4096
    num-queries-per-thread: 4096
    minimal-responses: yes
    access-control: 127.0.0.0/8 allow
