server:
    do-ip6: yes
    server-count: 4
    reuseport: yes
    minimal-responses: yes
    username: ""
    chroot: ""
    zonesdir: "__DIR__/zones"
    database: ""
    pidfile: "__RUN__/nsd-__NAME__.pid"
    zonelistfile: "__RUN__/nsd-__NAME__.zonelist"
    xfrdfile: "__RUN__/nsd-__NAME__.xfrd"
    logfile: "__RUN__/nsd-__NAME__.log"
# lib.sh appends the ip-address lines and the zone.
