server:
    interface: 127.0.0.1@__PORT__
    num-threads: 1
    username: ""
    chroot: ""
    directory: "__RUN__"
    pidfile: ""
    use-syslog: no
    logfile: ""
    verbosity: 1
    module-config: "validator iterator"
    trust-anchor-file: "__ANCHOR__"
    msg-cache-size: 512m
    rrset-cache-size: 1g
    outgoing-range: 8192
    num-queries-per-thread: 4096
    minimal-responses: yes
    ede: yes
    access-control: 127.0.0.0/8 allow
